apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bank-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: 542855644267.dkr.ecr.us-east-1.amazonaws.com/dev-backend:v1

        ports:
        - containerPort: 5000

        env:
        - name: PORT
          value: "5000"

        envFrom:
        - secretRef:
            name: backend-secret